implement the pwnstrip function
Gallopsled/pwntools pull request #1006
Opened 2017-07-30 05:03 UTC by junmoxiao

example:
pwn pwnstrip -p alarm -o a.out1 a.out
above command will make alarm has no effect.

2017-09-06 18:01 UTC, zachriggle requested changes

2017-09-06 18:01 UTC, zachriggle commented on pwnlib/commandline/pwnstrip.py
> +        elf.asm(offset, 'ret')
This doesn't work for e.g. ARM or MIPS.  Use `shellcraft.ret`.

2017-09-06 18:01 UTC, zachriggle commented on pwnlib/commandline/pwnstrip.py
> -    if args.output.isatty():
Please put this back <3

2017-09-06 18:01 UTC, zachriggle commented on pwnlib/commandline/pwnstrip.py
> +    if args.output:
`args.output` defaults to sys.stdout, this is unnecessary

2017-09-06 18:01 UTC, zachriggle commented on pwnlib/commandline/pwnstrip.py
> +        os.chmod(args.output, 0o755)
This needs to check if `args.output` is a file (`os.path.isfile`) OR needs to catch any exceptions that might get raised.

2017-09-06 18:01 UTC, zachriggle commented on pwnlib/commandline/pwnstrip.py
> -p.add_argument('-o', '--output', type=file, default=sys.stdout)
Please restore `default=sys.stdout`.

2017-09-06 18:01 UTC, zachriggle commented on pwnlib/commandline/pwnstrip.py
> +g.add_argument('-p', '--patch', metavar='FUNCTION',
Unnecessary whitespace changes

2017-09-06 18:01 UTC, zachriggle commented on pwnlib/commandline/pwnstrip.py
> +                elf.write(elf.address + offset + 0x10,
Unnecessary whitespace changes

2020-06-06 02:15 UTC, heapcrash commented
Closing this out since the PR is two+ years old.  Please rebase your changes on top of the current `dev` branch or create a new PR to get this merged.

2020-06-06 02:15 UTC, closed without merging