Fix for overwritten env when parsing core file
Gallopsled/pwntools pull request #1013
Opened 2017-08-09 07:22 UTC by cgsecurity

When analyzing core file where a stack based overflow occurred with a large payload, an assert was triggered when parsing the corrupted env.
```
  File "/usr/lib/python2.7/site-packages/pwnlib/elf/corefile.py", line 832, in _parse_stack
    assert self.unpack(envp_nullterm) == 0
```
This patch detects the problem before this assert and let us analyze the core file.

The problem is present in stable and dev branches.

2017-08-09 23:13 UTC, zachriggle commented
A few suggestions:

1. This should target the `stable` branch.  You can change this directly on Github in your browser.
2. The logging message should be more descriptive (e.g. "Found bad environment pointer at %#x")
3. The message should use `warn_once` instead of `debug`

2017-08-09 23:13 UTC, zachriggle requested changes
See previous comment

2017-08-10 06:40 UTC, cgsecurity commented
If I target the stable branch, it will pull all commits from the dev branch. Is that ok for you ?

2017-08-10 16:42 UTC, zachriggle commented
Good point.  You'll have to rebase your change onto `stable`, push it to Github (`git push --force`), then change the target branch.

2017-08-10 19:25 UTC, cgsecurity commented
I have created a new pull request for stable branch.

2017-08-10 19:25 UTC, closed without merging