Replace division with floor division as of PEP-238
Gallopsled/pwntools pull request #1135
Opened 2018-04-08 15:06 UTC by Arusekk

This will also get us closer to python3.
See https://www.python.org/dev/peps/pep-0238/

2018-04-09 19:35 UTC, zachriggle requested changes
Please add `from __future__ import division` to all source files, and ensure that the tests pass.

Thanks!

2018-04-09 19:35 UTC, zachriggle commented on pwnlib/constants/linux/s390.py
> +_SIGCONTEXT_NSIG_WORDS = Constant('_SIGCONTEXT_NSIG_WORDS',(64 // 64))
This is auto-generated from C source.  Please revert all changes to pwnlib/constants.

2018-04-09 21:14 UTC, Arusekk commented
Do you mean all python files by source files or just the ones involved in this commit?

2018-04-10 03:29 UTC, zachriggle commented
All source files that are not auto-generated (e.g. not pwnlib/data or pwnlib/constants).  There should be a flag you can pass to `six` or `futurize` that does this automagically.

2018-04-11 15:11 UTC, Arusekk commented
The tests successfully pass (but for the `runner` module, which is having some problems with coreutils binaries, possibly a wrong dynamic linker).

I'm ready with further adaptations for python3, in branch Arusekk/pwntools:full-3-compat
Just don't want to dump everything at once, nor to spam the pulls board.

2018-04-11 16:42 UTC, zachriggle commented
Thanks!

2018-04-11 16:42 UTC, merged