added ret2csu functionality
Gallopsled/pwntools pull request #1138
Opened 2018-04-15 16:35 UTC by CptGibbon

added a rop.ret2csu() call
should allow you to easily add ret2csu gadgets to an existing ROPchain

2018-04-16 18:30 UTC, zachriggle commented on pwnlib/rop/rop.py
> +            >>> print rop.dump()
These have to be actual tests, which means that this should print information out.

2018-04-16 18:30 UTC, zachriggle commented on pwnlib/rop/rop.py
> +            >>> print rop.dump()
Same here, this needs to be an actual test.  I'd recommend picking a binary from `pwnlib.data.elf`.

2018-04-16 18:31 UTC, zachriggle commented on pwnlib/rop/rop.py
> +        if context.bits != 64:
You need to check the `bits` property of the ELF, not `context`.

2018-04-16 18:32 UTC, zachriggle commented on pwnlib/rop/rop.py
> +        offset_g1 = 0x5a # delta between __libc_csu_init & 1st gadget
Don't hard-code an offset.  It'd be preferable to have a byte array that we search for.

2018-04-16 18:33 UTC, zachriggle commented on pwnlib/rop/rop.py
> +        for elf in exes:
Can we move this logic into the code that finds other gadgets?

I'd prefer if this could be found under `elf.symbols.libc_csu_init`.

2018-04-16 18:33 UTC, zachriggle commented on pwnlib/rop/rop.py
> +                elf.sym[u'__libc_csu_init'] = u64(elf.read(elf.entry + 0x19, 4).ljust(8, '\x00')) + elf.entry + 0x1d
Don't use the hard-coded offsets, thanks!

2018-04-16 18:34 UTC, zachriggle commented on pwnlib/rop/rop.py
> +            edi, rsi, rdx: Three primary registers to populate
We should probably check that the `edi` value can be packed with `p32()` (i.e., that it's a 32-bit value).

2018-04-16 18:35 UTC, zachriggle commented
Cool stuff!  Thanks for the contribution.  I've made some comments so that we can get this merged!

2018-04-16 18:36 UTC, zachriggle commented
Also, as a follow-up, it would be nice if we could integrate this into the logic for `ROP.setRegisters`.  Perhaps in another PR.

2018-04-17 13:21 UTC, CptGibbon commented on pwnlib/rop/rop.py
> +        offset_g1 = 0x5a # delta between __libc_csu_init & 1st gadget
Gotcha. Went for a capstone approach second time around.

2018-04-17 19:54 UTC, CptGibbon commented on pwnlib/rop/rop.py
> +        for elf in exes:
Humour me please I'm thick. Where exactly should this logic be integrated?

2018-04-18 14:32 UTC, Arusekk requested changes
The use of `x.has_key(y)` is obsolete. It is just a silly thing, but could make things easier in the future.

2018-04-18 14:32 UTC, Arusekk commented on pwnlib/rop/rop.py
> +                if elf.sym.has_key(u'__libc_csu_init'):
`x.has_key(y)` should be replaced with `y in x` to allow easier support of python3

2018-04-18 15:22 UTC, CptGibbon commented on pwnlib/rop/rop.py
> +                if elf.sym.has_key(u'__libc_csu_init'):
Appreciate it, done.

2018-05-25 20:15 UTC, zachriggle commented
Please merge `dev` or rebase, thanks!

2018-10-17 14:21 UTC, disconnect3d commented on pwnlib/rop/rop.py
> +                        break
Is it okay that we `break` only in this `if` and not in the previous one?

If we would like to break in both ifs we could write it as:

```python
if insn.mnemonic == 'mov' and insn.operands[0].reg in (X86_REG_R8, X86_REG_RCX):
    elf.sym[u'__libc_csu_init'] = insn.operands[1].imm
    break
```

2018-10-17 14:22 UTC, disconnect3d commented on pwnlib/rop/rop.py
> +                        break
Same above

2018-10-17 14:23 UTC, disconnect3d commented on pwnlib/rop/rop.py
> +        self.raw(0x01) # pop rbp
if those are eaten by `pop rbx; pop rbp` why don't we fill it? is it overwritten later on or what? (can we mention it in a comment?)

2018-10-17 16:12 UTC, CptGibbon commented on pwnlib/rop/rop.py
> +        self.raw(0x01) # pop rbp
In ret2csu the instructions:
`add rbx, 0x01`
`cmp rbx, rbp`
must conclude such that the next `jne` instruction does not jump.
I'll add a comment to this effect.

2018-12-26 05:35 UTC, zachriggle requested changes

2018-12-26 05:35 UTC, zachriggle commented on pwnlib/rop/rop.py
> +        csu_function = elf.read(elf.sym[u'__libc_csu_init'], elf.sym[u'__libc_csu_fini'] - elf.sym[u'__libc_csu_init'])
I feel like there's something broken elsewhere in Pwntools if we need to explicitly call out `unicode` strings in Python2.

Do you have a test case that fails without the `u'...'` prefix?

2018-12-27 11:24 UTC, CptGibbon commented on pwnlib/rop/rop.py
> +        csu_function = elf.read(elf.sym[u'__libc_csu_init'], elf.sym[u'__libc_csu_fini'] - elf.sym[u'__libc_csu_init'])
So far as I can tell this does not cause any failures.
I started using the `u'...'` prefix because `elf.sym` is a `dotdict` where the keys are of type `unicode` rather than `str`. I used it in some places but not others so purely for consistency I've used it across the function now.

2018-12-27 11:28 UTC, CptGibbon commented on pwnlib/rop/rop.py
> +                        break
These lines are correct, the arguments to `__libc_start_main()` are populated in this order and we use those instructions to resolve `__libc_csu_fini()` and `__libc_csu_init()`.
Since we know that the address of `__libc_csu_fini()` is resolved first we don't break after finding it, then we break only once `__libc_csu_init()` is resolved.

2020-02-09 17:45 UTC, closed without merging