Add support for coredumps which are stored using systemd-coredump
Gallopsled/pwntools pull request #1181
Opened 2018-08-03 21:24 UTC by jonasbb

From the `coredumpctl` man page:

> coredumpctl is a tool that can be used to retrieve and process
> core dumps and metadata which were saved by systemd-coredump(8).

`systemd-coredump` works by setting a piped core pattern. For example:

```bash
$ cat /proc/sys/kernel/core_pattern
|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e
```

This commit detects `systemd-coredump` in the pattern and then uses
`coredumpctl`, which is the CLI utility for reading the coredumps.
`coredumpctl` is instructed to write the coredump to a file. The
coredump is specified using the process ID and the basename of the
executable.

This commit also updates some doc strings to fix them and make them
more useful.

---

I kept the core in `native_corefile_pipe` for the `apport` case identical. I just changed the control flow to add another case.

I tried to keep `systemd_coredump_corefile` as simple as possible. The /dev/null files are requires, as otherwise `coredumpctl` would print quite a lot of status information about the coredump every time.

I did not add any test, because I do not know if and how that would be possible, as it would require an operating system with `systemd-coredump` configured. A docker container is not enough, as the `/proc` filesystem is mounted from the host.

2018-08-03 21:33 UTC, jonasbb commented on pwnlib/elf/corefile.py
> +            log.warn_once("Unsupported core_pattern: %r", self.kernel_core_pattern)
Switching to a `,` instead of the `%` fixes #1177.

2019-01-29 19:00 UTC, Arusekk requested changes
I think that the PR is great, have you tested it on your machine? I also submitted a review of changes that may be worth considering.

2019-01-29 19:00 UTC, Arusekk commented on pwnlib/elf/corefile.py
> +                stderr=open(os.devnull, 'w'),
I would suggest replacing the doubled `open()` call with stderr set to `STDOUT`
```suggestion
                stderr=subprocess.STDOUT,
```

2019-02-21 20:48 UTC, jonasbb commented
Hi @Arusekk, I included your feedback and rebased the PR to the current dev branch.

Yes I tested it locally, and it works fine.
```python
p = process(['./crash', payload])
c = p.corefile
# [*] Process './crash' stopped with exit code -11 (SIGSEGV) (pid 17058)                                               
# [x] Parsing corefile...
# [*] '/tmp/tmp/core.17058'
#     Arch:      i386-32-little
#     EIP:       0x80491d6
#     ESP:       0x6161616e
#     Exe:       '/tmp/tmp/crash' (0x8049000)
#     Fault:     0x6161616e
# [+] Parsing corefile...: Done
```

2019-02-22 02:14 UTC, Arusekk approved these changes

2019-02-22 02:18 UTC, merged