Fixed faulty read loop
Gallopsled/pwntools pull request #1239
Opened 2018-12-21 09:06 UTC by RobertLarsen

i386 linux stager had socket in wrong register and did not increment the destination pointer register after each read. This PR fixes this issue.

2018-12-26 13:04 UTC, zachriggle commented
Can you add a test for this?  Probably easiest to use the [runners](http://docs.pwntools.com/en/stable/runner.html) to exec your shellcode.

2018-12-27 23:27 UTC, RobertLarsen commented
That should be doable, but how do I run a doctest from inside a template?

2019-01-14 09:06 UTC, RobertLarsen commented
@zachriggle I added a doctest the same way as the echo shellcode did it but I don't know how to actually run it. However, if I run the code manually I get the expected result.

2019-01-15 10:12 UTC, zachriggle requested changes

2019-01-15 10:12 UTC, zachriggle commented on pwnlib/shellcraft/templates/i386/linux/stager.asm
> +	>>> for c in stage_2:
Your indentation is incorrect here.  Looks like you added a tab.  The error on Travis is a bit misleading, but this is the reason.

```
**********************************************************************
File "shellcraft/i386.rst", line ?, in default
Failed example:
    for c in stage_2:
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/2.7.14/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/sphinx/ext/doctest.py", line 480, in compile
        return compile(code, name, self.type, flags, dont_inherit)
      File "<doctest default[2]>", line 1
        for c in stage_2:
                        ^
    SyntaxError: unexpected EOF while parsing
```

2019-01-16 01:31 UTC, merged