Launch QEMU with sysroot if specified
Gallopsled/pwntools pull request #1241
Opened 2018-12-27 23:42 UTC by gsingh93

When launching an ARM binary with QEMU using `gdb.debug`, we need to specify the `-L` flag to tell QEMU where the sysroot is. Otherwise it will use the default system root instead of the one we specified.

2019-02-02 09:21 UTC, zachriggle commented
@gsingh93 can you double-check that my change (should be cosmetic only) still works for your use-case?

2019-02-18 03:44 UTC, gsingh93 commented
@zachriggle no, `qemu_user` is missing from the `qemu_args` array on line 432. We also need to add add this flag along with the `-g` flag, which was way in my commit I'm appending the original arguments (containing the `-g` flag) after I added the `-L` flag.

2019-04-29 06:18 UTC, gsingh93 commented
ping @zachriggle

2019-05-22 00:00 UTC, zachriggle requested changes

2019-05-22 00:00 UTC, zachriggle commented on pwnlib/gdb.py
> +            qemu_args = ['-L', sysroot]
Looks like we discard the previous QEMU args this way?

2019-05-22 00:01 UTC, zachriggle approved these changes

2019-12-09 17:04 UTC, merged