[dev3] Minor changes for python3 support
Gallopsled/pwntools pull request #1310
Opened 2019-05-17 14:35 UTC by mcd1992

Remove downgrade requirement for sortedcontainers and intervaltree.
Change the call to intervaltree's search in elf/elf.py to the new overlap function
Spit out usage text if pwn commandline bin is called without arguments.

With these changes I was able to get it working fine on arch without requiring any downgraded packages or other weird tricks. Not entirely sure if this is python 2 incompatible. From what I can see python2 has errno in its own library, the latest py2 intervaltree has search split into overlap/envelop so I'd imagine its fine.

2019-05-20 16:33 UTC, Arusekk approved these changes
Nice done! Thank you for doing this, I thought that it would be harder. A minor change is required for the automated requirement systems to update libraries (e.g. Travis CI)

2019-05-20 16:33 UTC, Arusekk commented on setup.py
> +                        'intervaltree',
Actually, would be nice to explicitly state that old intervaltree won't work.
```suggestion
                        'intervaltree>=3.0',
```

2019-05-20 16:36 UTC, Arusekk requested changes
Please merge the suggestion first

2019-05-22 00:04 UTC, zachriggle commented
Looks like this breaks Python2.  Separately, @Arusekk, we should probably change the CI to use Python3.7

2019-05-22 06:13 UTC, Arusekk commented
Well, as for py2, pip plans to drop its support as soon as it gets EOL'd. But in this case it seems to be a fault of CI

2019-06-11 06:15 UTC, Arusekk commented
For reference: pypa/pip#6275

We can install separately requirements before installing the project, or not use --editable, or build egg info separately

2019-06-22 19:29 UTC, Arusekk approved these changes

2019-06-22 19:50 UTC, merged