gdb.debug() environment variables fix
Gallopsled/pwntools pull request #1539
Opened 2020-06-02 23:39 UTC by jlewis200

If passed an empty dictionary defining the environment variables, the process invoked by gdb.debug() has environment variable 'PWD' set to the directory containing the executable.  This behaviour is not observered when NOPTRACE is enabled:  the program runs without any environment variables set.  Similarly, if an empty environment variable dictionary is passed to process(), it appears to also run under a truly empty environment.  Additionally, attempts to overwrite the "PWD" environment variable with a dictionary entry are not successful under gdb.debug().

This fix brings the gdb.debug() treatment of environment variables in line with process() and gdb.debug() with NOPTRACE enabled. 
 It allows both empty environments, and overwriting of the 'PWD' environment variable.

# Pwntools Pull Request

Thanks for contributing to Pwntools!  Take a moment to look at [`CONTRIBUTING.md`][contributing] to make sure you're familiar with Pwntools development.

Please provide a high-level explanation of what this pull request is for.

## Testing

Pull Requests that introduce new code should try to add doctests for that code.  See [`TESTING.md`][testing] for more information.

## Target Branch

Depending on what the PR is for, it needs to target a different branch.

You can always [change the branch][change] after you create the PR if it's against the wrong branch.

| Branch   | Type of PR                                                       |
| -------- | ---------------------------------------------------------------- |
| `dev`    | New features, and enhancements
| `dev`    | Documentation fixes and new tests
| `stable` | Bug fixes that affect the current `stable` branch
| `beta`   | Bug fixes that affect the current `beta` branch, but not `stable`
| `dev`    | Bug fixes for code that has never been released

[contributing]: https://github.com/Gallopsled/pwntools/blob/dev/CONTRIBUTING.md
[testing]: https://github.com/Gallopsled/pwntools/blob/dev/TESTING.md
[change]: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

2020-06-03 05:54 UTC, Arusekk requested changes
Great! I did not know that there is a difference. Please add my change, and I will merge this.

2020-06-03 05:54 UTC, Arusekk commented on pwnlib/gdb.py
> +    if env != None:
Identity comparison is faster and generally recommended by Python docs when dealing with `None`:
```suggestion
    if env is not None:
```

2020-06-03 13:56 UTC, jlewis200 commented
> Great! I did not know that there is a difference. Please add my change, and I will merge this.

It appears to be a gdbserver quirk.  gdbserver is launched in the specified environment, but the debugged process always always has PWD set unless using the env wrapper with the -i option..

2020-06-08 00:05 UTC, merged

2020-06-08 00:17 UTC, heapcrash commented
I merged this since it's a useful way to set the environment, but I can't reproduce a single-env-var process with `gdb.debug`.

```py
ELF.from_assembly(shellcraft.sh()).debug(env={'foo': 'bar\x01\x02\x03\xff'})
```

Still shows PWD

```
pwndbg> env
00:0000│   0xffc7581c —▸ 0xffc75fad ◂— 0x3d6f6f66 ('foo=')
01:0004│   0xffc75820 —▸ 0xffc75fb9 ◂— 0x3d445750 ('PWD=')
02:0008│   0xffc75824 ◂— 0x0
```

2020-06-08 02:07 UTC, jlewis200 commented
> I merged this since it's a useful way to set the environment, but I can't reproduce a single-env-var process with `gdb.debug`.
> 
> ```python
> ELF.from_assembly(shellcraft.sh()).debug(env={'foo': 'bar\x01\x02\x03\xff'})
> ```
> 
> Still shows PWD
> 
> ```
> pwndbg> env
> 00:0000│   0xffc7581c —▸ 0xffc75fad ◂— 0x3d6f6f66 ('foo=')
> 01:0004│   0xffc75820 —▸ 0xffc75fb9 ◂— 0x3d445750 ('PWD=')
> 02:0008│   0xffc75824 ◂— 0x0
> ```

I see what you mean.  This method seems to work fine when used with preexisting executables, but not the ELF.from_assembly() case you showed above.