SSH enhancements (use allow_agent instead of os.environ.pop, allow user to opt out of using ~/.ssh)
Gallopsled/pwntools pull request #1566
Opened 2020-06-07 15:17 UTC by saleemrashid

- Use Paramiko's `allow_agent` parameter instead of `os.environ.pop('SSH_AUTH_SOCK', None)` (which affects the entire Python process) - I need to test this, and confirm which version of Paramiko this feature was added in

- Allow the user to opt out of using `~/.ssh` (fixes #1519) with a new parameter, `use_environment` (which defaults to `True` to keep the old behaviour). This _isn't_ the solution I proposed in that issue because I suspect allowing the user to pass in the `client` is a huge footgun; you still need the `host`, `port` fields, etc. but you might end up with "drift" where these don't correspond to the `client` the user passed in (Paramiko doesn't keep track of these, as far as I know).

Opening this pull request as a draft because I haven't tested it yet.

2020-06-09 00:45 UTC, heapcrash commented
I'd rather `use_environment` is called `ssh_config` and perhaps we set the default value to `~/.ssh/config`.  A user can then specify `ssh_config=None` to get this behavior.  WDYT?

2020-06-11 22:39 UTC, saleemrashid commented
@heapcrash Sure! One thing I'm thinking is that `use_environment` covers three things:

1. Reading `~/.ssh/config`
2. Reading and writing `~/.ssh/known_hosts`
3. Paramiko's `look_for_keys` option

If we had a `ssh_config` for the first one, would you want that to cover the other two? Or should we have three separate options?

2020-06-13 00:18 UTC, zachriggle commented
I think separate flags would be the best way, "use_environment" indicates
something is coming from environment variables (or not), although this
makes it more verbose to disable all of the settings.

*Zach Riggle*


On Thu, Jun 11, 2020 at 5:40 PM Saleem Rashid <notifications@github.com>
wrote:

> @heapcrash <https://github.com/heapcrash> Sure! One thing I'm thinking is
> that use_environment covers three things:
>
>    1. Reading ~/.ssh/config
>    2. Reading and writing ~/.ssh/known_hosts
>    3. Paramiko's look_for_keys option
>
> If we had a ssh_config for the first one, would you want that to cover
> the other two? Or should we have three separate options?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Gallopsled/pwntools/pull/1566#issuecomment-642966624>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA3IGFGEY6PIF5MRRDWAJ3RWFMMHANCNFSM4NXKTXZQ>
> .
>

2020-06-13 15:37 UTC, Arusekk commented
I would personally call the variable something like isolated, with
inverted meaning.

2020-06-13 21:16 UTC, zachriggle commented
I'm down for `isolated` or `ignore_config` or something like that 👍 and having it be a single toggle

2020-06-16 04:14 UTC, heapcrash commented
I would prefer this fix to #1578

2020-06-24 02:54 UTC, heapcrash requested changes

2020-06-24 02:54 UTC, heapcrash commented on pwnlib/tubes/ssh.py
> +        if use_environment:
Just to make the patchset smaller, can we move this check to e.g.

```
if use_environment and os.path.exists(config_file)
```

2020-06-24 02:54 UTC, heapcrash commented on pwnlib/tubes/ssh.py
> +            use_environment: If :const:`False`, disable usage of ~/.ssh/config and ~/.ssh/authorized_keys
Can we change this to `isolated` or `ignore_config` or `ignore_dotfiles` per the main discussion?

2020-07-04 01:34 UTC, heapcrash requested changes
We can make the change much smaller with e.g. `if use_environment and os.path.exists(...)` rather than re-indenting everything (which makes merges harder).

2020-07-04 20:51 UTC, saleemrashid commented
Updated to address review comments. Haven't been able to test yet (see my original comment).

2020-07-07 22:06 UTC, Arusekk approved these changes

2020-07-10 05:45 UTC, heapcrash commented
Looks like all this is missing is a changelog entry

2020-09-27 21:12 UTC, Arusekk approved these changes

2020-11-01 11:37 UTC, Arusekk commented
Sadly no tests for now, but we can just wait for bug reports when people start using this.

2021-04-29 17:20 UTC, merged