Add misc.bytes_iter and misc.bytes_list
Gallopsled/pwntools pull request #1568
Opened 2020-06-09 00:58 UTC by heapcrash

Fixes #1532

2020-06-09 05:32 UTC, Arusekk commented
In most places we now use an idiom `for charcode in bytearray(bytes_object):`. WDYT? If we want to introduce compatibility functions, I would prefer adding ones that emulate py3 behavior under py2 (easier to maintain / eventually drop py2 support in some AD 2100), unless this would prove explicitly useful in several places.

2020-10-20 20:43 UTC, Arusekk requested changes
I don't think we need this. We already use bytearray heavily.

2020-10-20 20:43 UTC, Arusekk commented on pwnlib/util/misc.py
> +       'dh': ['edx', 'dx', 'dh'],
Whoa! Ugly accidental whitespace changes
```suggestion
         'dh': ['edx', 'dx', 'dh'],
```

2020-10-25 15:38 UTC, zachriggle commented
Thanks for digging into this @Arusekk

2021-05-31 20:36 UTC, heapcrash commented
Need to follow up on this one.

2023-07-09 12:16 UTC, Arusekk commented
Pretty sure this is not very useful; closing for now, we can revisit this if needed.

2023-07-09 12:16 UTC, closed without merging