Enhance gdb error message when unable to launch binary
Gallopsled/pwntools pull request #1614
Opened 2020-06-28 00:39 UTC by Arusekk

A common issue is when the binary is not executable,
or the binary is simply missing.

2020-06-28 00:56 UTC, heapcrash commented
Is this the case where the main binary isn't executable, or that gdb is not executable?

I would rather fix this in `attach` or `debug` by directly checking if the file is executable, rather than handling an error from `gdb`.

2020-06-28 00:56 UTC, heapcrash requested changes

2020-06-28 00:56 UTC, heapcrash commented on pwnlib/gdb.py
> +        log.error('gdbserver did not output its pid (maybe chmod +x?): %s', process_created.decode())
`decode` => `six.ensure_string`

2020-07-04 01:33 UTC, heapcrash commented
Can we actually check permissions rather than looking for things that break when they're wrong?

2020-07-07 07:06 UTC, Arusekk commented
Well, this is just the common case, but there may be more subtle things, like wrong PT_INTERP or stuff. Just not all cases can be included here, and it forwards the error that the shell (run by gdbserver) gives, so the user can see the original error message, and not the last word of it in weird context (e.g. `Invalid int for base 10: 'denied'` instead of proper `sh: /foo/bar: Permission denied`). The message may be worth rewording, but I believe this kind of change is necessary.

2020-07-12 04:39 UTC, merged