I386 ascii shellcode
Gallopsled/pwntools pull request #1667
Opened 2020-08-26 10:01 UTC by TwoUnderscorez

I've written a module based on the Riley "Caezar" Eller's technique to bypass data filters, for buffer overflow exploits, on Intel x86 platforms.
http://julianor.tripod.com/bc/bypass-msb.txt
The algorithm to calculate the subtractions for warping around eax is based on https://github.com/VincentDary/PolyAsciiShellGen

2020-08-27 19:37 UTC, heapcrash commented
It looks like your change to changelog.md modifies a lot of lines it shouldn't.  Can you fix this? (git checkout origin/master -- CHANGELOG.md then add your change again)

2020-08-28 07:14 UTC, TwoUnderscorez commented
Sorry, my bad. I guess my IDE's auto-formatting kicked in and I've just not noticed. Hopefully it's good now.

2020-09-05 11:55 UTC, TwoUnderscorez commented
I did not realize you still support Python 2, so now that's fixed.

2020-09-05 22:56 UTC, zachriggle requested changes

2020-09-05 22:56 UTC, zachriggle commented on docs/source/ascii_shellcode.rst
> +      bytes2hex = bytes.hex
Instead of doing hex2bytes etc, we have some custom hooks in the doctest engine which does "the right thing" as long as you specify a `b` prefix for your bytes.

So you can do:

```py
>>> b'asdf'
b'asdf'
```

And everything works on both Python2 and Python3

2020-09-05 22:56 UTC, zachriggle commented on pwnlib/ascii_shellcode.py
> +        >>> sc = hex2bytes('83c41831c031dbb006cd8053682f747479682f64657689e331c966b91227b005cd806a175831dbcd806a2e5853cd8031c050682f2f7368682f62696e89e3505389e199b00bcd80')
I would prefer we also have an `ELF.from_bytes().process()` test that actually runs some shellcode to ensure that it works.  e.g.

```
>>> sc = shellcraft.echo("Hello world") + shellcraft.exit()
>>> ascii = ascii_shellcode(asm(sc))
>>> ELF.from_bytes(ascii).process().recvall()
b"Hello world"
```

2020-09-08 18:45 UTC, TwoUnderscorez commented on docs/source/ascii_shellcode.rst
> +      bytes2hex = bytes.hex
Fixed.

2020-09-08 18:52 UTC, TwoUnderscorez commented on pwnlib/ascii_shellcode.py
> +        >>> sc = hex2bytes('83c41831c031dbb006cd8053682f747479682f64657689e331c966b91227b005cd806a175831dbcd806a2e5853cd8031c050682f2f7368682f62696e89e3505389e199b00bcd80')
Added doctest.
Since the shellcode is executing from the code segment and is being unpacked onto the stack, I had to add a `jump esp` to the end of the unpacker.
(Usually, the unpacker also runs on the stack, and when `eip` bumps into `esp` the unpacked shellcode starts executing).

2020-09-13 18:36 UTC, Arusekk commented
This code must be moved under `pwnlib.encoders.i386`.

2020-09-20 12:58 UTC, TwoUnderscorez commented
@Arusekk moved under `pwnlib.encoders.i386`.

2020-09-20 15:16 UTC, Arusekk requested changes
Ooofff. That's some great stuff! But I would like it better if it changed a bit. Here you have my MASSIVE review you will find helpful.

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +                subtractions.append(bytearray(b'\x00'*int_size))
This would be enough:
```suggestion
                subtractions.append(bytearray(int_size))
```

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +        int_size = context.bits // 8
We already have a shortcut for this :)
```suggestion
        int_size = context.bytes
```

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +        int_size = context.bits // 8
As below
```suggestion
        int_size = context.bytes
```

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +        for products in product(*[vocab for _ in range(2)]):
Why so unnaturally?
```suggestion
        for products in product(vocab, vocab):
```

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +                    return tuple(int.from_bytes(x.to_bytes(1, 'little')*int_size, 'little') for x in products)
would be easier to just do some
```suggestion
                    return tuple(unpack(p8(x)*int_size) for x in bytearray(products))
```
or
```suggestion
                    MAGIC = (1 << context.bits) // 255  # 0x01010101 when 32 bits
                    return tuple(x * MAGIC for x in bytearray(products))
```
which would work for both py2 and py3 (maybe omit `bytearray(` if products are guaranteed to yield ints)

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +                result += struct.pack('=c{}s'.format(int_size), b'-', subtraction)
maybe too complex?
```suggestion
                result += b'-' + subtraction
```

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +                sc.append(''.join(byte))
What does it serve? Wouldn't it be simpler to write:
```py
    sc = tuple(group(int_size, bytearray(shellcode), 0x90))[::-1]
```
as a universal code?

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +        int_size = context.bits // 8
Hat-trick!
```suggestion
        int_size = context.bytes
```

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +                    attempt = sum(chain(
I guess it would be more readable to just write
```suggestion
                    attempt = target[byte] + carry + sum(products)
```

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +                        products = map(lambda x: isinstance(x, str) and ord(x) or x, products)
This should be redundant if carefully planned

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +encode = AsciiShellcodeEncoder()
Your editor could use some adjustments, as git is generally sad about no final newline (this project does not require it, though, so don't worry if you fix everything else).

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +        result += struct.pack('=cIcI', b'%', pos, b'%', neg)
I think that `'<'` would be better than `'='` in `struct.pack`s, in case someone tries to pwn a x86 box from a big-endian network router or something else (which pwntools devs generally do not guarantee to work, but let's try to be portable when it costs nothing).
```suggestion
        result += struct.pack('<cIcI', b'%', pos, b'%', neg)
```

You can always use our great `packing.flat`!
```suggestion
        result += flat((b'%', pos, b'%', neg))
```

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +            result += struct.pack('=c{}s'.format(int_size), b'-', subtraction)
why not just
```suggestion
            result += b'-' + subtraction
```

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +                subtraction = str(subtraction)
why?

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +        target = struct.pack('=I', size)
see below
```suggestion
        target = struct.pack('<I', size)
```
or
```suggestion
        target = pack(size)
```

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +        int_size = context.bits // 8
see other
```suggestion
        int_size = context.bytes
```

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +            allowed = set(map(ord, all_chars))
Is `all_chars` really a string? It should be a bytearray, so you could just do a `set(all_chars)`... nevermind

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +        subtractions = [bytearray(b'\x00'*int_size)]
In case you didn't know
```suggestion
        subtractions = [bytearray(int_size)]
```

2020-09-20 15:16 UTC, Arusekk commented on pwnlib/encoders/i386/ascii_shellcode.py
> +            target = map(ord, target)
This can be solved universally using bytearray

2020-09-20 15:21 UTC, Arusekk commented on pwnlib/ascii_shellcode.py
> +        >>> sc = hex2bytes('83c41831c031dbb006cd8053682f747479682f64657689e331c966b91227b005cd806a175831dbcd806a2e5853cd8031c050682f2f7368682f62696e89e3505389e199b00bcd80')
FYI we also have a `run_shellcode` shortcut somewhere (with a similar `debug_shellcode` to aid development) that accepts bytes and returns a running process tube, just as above.

2020-09-20 19:07 UTC, TwoUnderscorez commented
Thanks for taking the time to review my code! I'll fix all the cosmetic / pack / bytearray stuff soon. As for python 2 <-> 3 compatible code, It'll probably take me a little longer since I'm less familiar with writing backwords compatible code.

2020-09-20 20:20 UTC, Arusekk commented
Don't worry, it is here all about using bytearray and avoiding ord / chr and consrtucts that are obsolete or too fresh

2020-09-25 09:42 UTC, TwoUnderscorez commented on pwnlib/encoders/i386/ascii_shellcode.py
> +            target = map(ord, target)
Resolved here https://github.com/Gallopsled/pwntools/pull/1667/commits/d685b4174d1dd5e3db28f4d3b4a7f9d2021e5eb2

2020-09-25 09:43 UTC, TwoUnderscorez commented on pwnlib/encoders/i386/ascii_shellcode.py
> +                subtraction = str(subtraction)
Deleted. https://github.com/Gallopsled/pwntools/pull/1667/commits/d685b4174d1dd5e3db28f4d3b4a7f9d2021e5eb2

2020-09-25 09:44 UTC, TwoUnderscorez commented on pwnlib/encoders/i386/ascii_shellcode.py
> +            allowed = set(map(ord, all_chars))
I'm entirly sure what you mean, but I think I fixed it here https://github.com/Gallopsled/pwntools/pull/1667/commits/d685b4174d1dd5e3db28f4d3b4a7f9d2021e5eb2.

2020-09-25 09:45 UTC, TwoUnderscorez commented on pwnlib/encoders/i386/ascii_shellcode.py
> +                sc.append(''.join(byte))
Fixed https://github.com/Gallopsled/pwntools/pull/1667/commits/d685b4174d1dd5e3db28f4d3b4a7f9d2021e5eb2

2020-09-25 09:46 UTC, TwoUnderscorez commented on pwnlib/encoders/i386/ascii_shellcode.py
> +                        products = map(lambda x: isinstance(x, str) and ord(x) or x, products)
Deleted https://github.com/Gallopsled/pwntools/pull/1667/commits/d685b4174d1dd5e3db28f4d3b4a7f9d2021e5eb2

2020-09-26 08:56 UTC, Arusekk approved these changes

2020-09-26 08:59 UTC, merged