Fix documentation of #1667
Gallopsled/pwntools pull request #1693
Opened 2020-10-03 09:39 UTC by TwoUnderscorez

This pull request is just to fix how the documentation of #1667 looks on docs.pwntools.com which currently looks like [this](http://docs.pwntools.com/en/latest/encoders.html?highlight=encoders#pwnlib.encoders.i386.ascii_shellcode.AsciiShellcodeEncoder) (which is horrible).
The goal is that it would something like this:
![image](https://user-images.githubusercontent.com/25303006/94988225-56784580-0574-11eb-9c90-d1bebd07a0c9.png)
_(Also allows users to change `max_subs` which I forgot to do)_

2020-10-04 11:53 UTC, Arusekk requested changes

2020-10-04 11:53 UTC, Arusekk commented on CHANGELOG.md
> +| [2.2.0](#220)   |          | Jan 5, 2015           |
😡

2020-10-04 11:53 UTC, Arusekk commented on docs/source/encoders.rst
> +   :exclude-members: __init__
Does this exclude also the tests by chance?

2020-10-04 15:10 UTC, TwoUnderscorez commented on CHANGELOG.md
> +| [2.2.0](#220)   |          | Jan 5, 2015           |
Sorry 😅
1ab2a4114bed0b7ff6f91b2c7cf11937d2a3393e

2020-10-04 15:30 UTC, TwoUnderscorez commented on docs/source/encoders.rst
> +   :exclude-members: __init__
The goal here was to include the `__call__` method in the documentation so I included all the special members and then excluded `__init__` because if I don't exclude it, it'll show up twice (which doesn't have any doctests anyway). I also added `assert False` to all the functions just to be sure, and they all ran.

2020-10-04 18:57 UTC, Arusekk commented
sorrrrrry my bad

2020-10-05 05:26 UTC, TwoUnderscorez commented
@Arusekk I'm sorry if I missed something, but were you not satisfied with my replies to your review? When do you think this can be merged?

2020-10-05 09:08 UTC, merged

2020-10-05 09:09 UTC, Arusekk commented
This is awesome and great thanks!