Refactor pwnlib.encoders.encode() to be more nice to bytes objects
Gallopsled/pwntools pull request #1923
Opened 2021-06-25 11:01 UTC by heapcrash

* Add byteset() to misc which does "the right thing" and returns a set of `bytes` objects
* Make bytes_avoid be a bytes() object instead of a set
* Update documentation to note that functions take bytes() and not str()

# Example Script (ex.py)

```py
from pwn import *
sc = asm(shellcraft.sh())
avoid=b'/bin'
enc = encode(sc, avoid=avoid)
assert not (byteset(avoid) & byteset(enc))
io = ELF.from_bytes(enc).process()
io.sendline('whoami')
print(io.recvline('pwntools'))
```

## Python3

```
$ python3 ex.py SILENT
b'pwntools\n'
```

## Python2

```
$ python2 ex.py SILENT
pwntools
```

2021-06-25 13:08 UTC, Arusekk commented
Personally I would prefer the set to be a set of numbers, but looks good.

2021-06-25 13:10 UTC, heapcrash commented
> Personally I would prefer the set to be a set of numbers, but looks good.

The issue with this is the difference between Py2 and Py3.  I think there's value in keeping the behavior of the two as close as possible, for making the code as simple as possible.

### Py2

```
>>> set(b'asdf')
{'a', 'd', 'f', 's'}
```

### Py3

```
>>> set(b'asdf')
{97, 100, 102, 115}
>>> byteset(b'asdf')
{b'a', b'd', b'f', b's'}
```

2021-06-25 13:15 UTC, Arusekk commented
Yes, I only meant the new common behavior to be based on what py3 already does normally, and only adding a layer of py2 compatibility. This will make it easier to drop py2 support eventually (since we want to drop it in some Pwntools 5000, right?).

-- 
Wysłane z mojego urządzenia Sailfish

2021-06-25 14:15 UTC, heapcrash commented
I hereby vote the next release is Pwntools v5.000 😛

2021-07-08 17:04 UTC, heapcrash commented
I vote even when we drop Py2 support entirely, having a `byteset` or
similar construct is useful, as would be an e.g. bytesiter.  Working with
bytes() ALL THE TIME is much easier than working with int() on occasion.

On Fri, Jun 25, 2021 at 8:15 AM Arusekk ***@***.***> wrote:

> Yes, I only meant the new common behavior to be based on what py3 already
> does normally, and only adding a layer of py2 compatibility. This will make
> it easier to drop py2 support eventually (since we want to drop it in some
> Pwntools 5000, right?).
>
> --
> Wysłane z mojego urządzenia Sailfish
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Gallopsled/pwntools/pull/1923#issuecomment-868491893>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APYTIFJHWJKG5L3OWLNBW3TTUR6PZANCNFSM47JVFSZA>
> .
>

2021-08-15 21:35 UTC, peace-maker requested changes
Thank you! Allowing to run the encoders again at least is great.

2021-08-15 21:35 UTC, peace-maker commented on pwnlib/encoders/encoder.py
> +    avoid = byteset(avoid or '')
This should be `b''`.

2021-08-15 21:35 UTC, peace-maker commented on pwnlib/encoders/encoder.py
>  re_alphanumeric  = r'[^A-Za-z0-9]'
These patterns have to be bytes as well, to make the below functions work.
`TypeError: cannot use a string pattern on a bytes-like object`

2023-07-25 08:57 UTC, peace-maker commented
I agree with having a `byteset` and maybe `byteiter` helper. It's not really 100% relevant to this PR, but *a* way to implement it. You don't have to use it, but there were occasions where I wanted the bytes and had to `p8(x)` again while looping over some `bytes`.

2023-07-31 19:56 UTC, peace-maker commented on docs/source/encoders.rst
> -.. automodule:: pwnlib.encoders.i386.ascii_shellcode
The ASCII encoder isn't added to the encoder mapping in the Encoder class. We should keep the docs for that one, since it has to be used explicitly.

It has extra settings worth documenting and decodes the shellcode onto the stack, so a `jmp esp` is required afterwards.

2025-03-05 11:17 UTC, Arusekk commented
Since we are dropping py2, I think this has become counterproductive.

2025-03-05 11:17 UTC, closed without merging