TMP commit for draft PR
Gallopsled/pwntools pull request #1931
Opened 2021-07-11 14:58 UTC by gogo2464

This is a draft PR to show it to a friend. Please ignore it for the moment.

# Pwntools Pull Request

Thanks for contributing to Pwntools!  Take a moment to look at [`CONTRIBUTING.md`][contributing] to make sure you're familiar with Pwntools development.

Please provide a high-level explanation of what this pull request is for.

## Testing

Pull Requests that introduce new code should try to add doctests for that code.  See [`TESTING.md`][testing] for more information.

## Target Branch

Depending on what the PR is for, it needs to target a different branch.

You can always [change the branch][change] after you create the PR if it's against the wrong branch.

| Branch   | Type of PR                                                       |
| -------- | ---------------------------------------------------------------- |
| `dev`    | New features, and enhancements
| `dev`    | Documentation fixes and new tests
| `stable` | Bug fixes that affect the current `stable` branch
| `beta`   | Bug fixes that affect the current `beta` branch, but not `stable`
| `dev`    | Bug fixes for code that has never been released

[contributing]: https://github.com/Gallopsled/pwntools/blob/dev/CONTRIBUTING.md
[testing]: https://github.com/Gallopsled/pwntools/blob/dev/TESTING.md
[change]: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

## Changelog

After creating your Pull Request, please add and push a commit that updates the changelog for the appropriate branch.  
You can look at the existing changelog for examples of how to do this.

2021-07-12 20:21 UTC, Arusekk requested changes
Thanks for submitting the PR, I see that it is not yet marked ready for review, but I thought I should point some things out as early as possible to save your time, especially that the PR has been here for a while now, and it looks like you would like to integrate some of it into pwntools, for real. Marking as Changes Requested only to mark the PR as not ready (in the current shape).

I see that there are still some verbose debugs scattered throughout the core modules; try to put these into separate temporary scripts, like `winwin.py` or `todo123.py`.

As for the unconditional `import windows`, they are all too much, and break normal standards-compliant oses, and should be put preferably into a separate tube, or imported from a separate module on a use-site basis. In files like `pwnlib/tubes/winprocess.py` or `pwnlib/util/ntcompat.py`. They should implement nt-specific additional features and workarounds for the missing functionalities of nt, which all other oses already have, or if some feature is completely missing from nt, and implemented upside down, they should be made into a new class. Of course if you have a better idea, it will be OK, as long as it cannot be called unelegant.

2021-07-12 20:21 UTC, Arusekk commented on requirements.txt
> +git+git://github.com/hakril/PythonForWindows
First thing, you should rather urge hakril to make a beta release than add a 'live' version here, and second thing, move any dependency declaration to setup.py where they belong in pwntools (I would personally prefer requirements.txt too, but if they are all there, there is no valid reason to add them here).

2021-07-12 20:21 UTC, Arusekk commented on pwnlib/tubes/process.py
> +            self.debuggerpath = r'C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\windbg.exe'
Pinning `C`, `x64`, `x86` and `10`, huh? Not too great, maybe use [`glob`](https://docs.python.org/dev/library/glob.html), and variables like `os.environ['PROGRAMFILES(X86)']`, if not some registry, I guess (I have not done any nt for ages, so no idea how it works now).

Is this `debuggerpath` attribute even used anywhere else, or am I missing something?

2021-07-12 20:21 UTC, Arusekk commented on pwnlib/tubes/process.py
> +        if context.os == "linux":
Hey hey, no need to be so cautious, how is this even desired? What about `p.terminate()` or `p.returncode`, for example?

2021-07-12 20:21 UTC, Arusekk commented on pwnlib/tubes/process.py
> +        if context.os == "windows":#TODO : close the windows process
Handles need to be closed, too; python has the concept of 'file-like' objects, that should be implemented transparently for nt pipes as well as standard pipes. Why not use the handles returned by Python API with e.g. `.fileno()`?

2021-07-12 20:21 UTC, Arusekk commented on pwnlib/tubes/process.py
> +        if context.os == "linux":
Try to `if` out only the pieces of code that actually don't work; clearly the `if self.proc is None:` is os-agnostic, so is `self.poll`.

2021-07-12 20:21 UTC, Arusekk commented on pwnlib/tubes/process.py
> +    """Windows pipe support"""
I thought [`os.pipe`](https://docs.python.org/dev/library/os.html#os.pipe) was capable of creating windows anonymous pipes as well.

2021-07-12 22:06 UTC, gogo2464 commented
All your comments are true. My PR is currently just a copy and paste of https://github.com/masthoon/pwintools/blob/master/pwintools.py but at this moment my proirity is to make it just work. pwintools does not works on python3. Then I even need a PR for pwintools and even for PythonForWindows which works only in python3 see: https://github.com/hakril/PythonForWindows/issues/23.

When I will have fixed all that I will check out your comments.

2022-12-28 23:35 UTC, Arusekk commented
Closing as this is almost 100% not-ready, and there has been no positive feedback happening in this PR.

2022-12-28 23:35 UTC, closed without merging