Add js_escape and js_unescape
Gallopsled/pwntools pull request #1979
Opened 2021-10-08 04:30 UTC by justinsteven

This adds `util.packing.js_escape()` and `util.packing.js_unescape()`

These are useful for preparing binary data in such a way that it can be placed in memory using a JavaScript engine.

I'm not completely sure that I'm using `@LocalNoarchContext` correctly, or that my function signatures/docstrings are correct.

# Demo

```plain
>>> import pwn

>>> pwn.js_escape(pwn.cyclic(64))
'%u6161%u6161%u6162%u6161%u6163%u6161%u6164%u6161%u6165%u6161%u6166%u6161%u6167%u6161%u6168%u6161%u6169%u6161%u616a%u6161%u616b%u6161%u616c%u6161%u616d%u6161%u616e%u6161%u616f%u6161%u6170%u6161'

>>> pwn.js_unescape(pwn.js_escape(pwn.cyclic(64))) == pwn.cyclic(64)
True
```

Using IE11, this cyclic pattern can be put into memory with:

```html
<html>
<body>
<div id="my_div">
<script>
var data = unescape("%u6161%u6161%u6162%u6161%u6163%u6161%u6164%u6161%u6165%u6161%u6166%u6161%u6167%u6161%u6168%u6161%u6169%u6161%u616a%u6161%u616b%u6161%u616c%u6161%u616d%u6161%u616e%u6161%u616f%u6161%u6170%u6161");
var div_container = document.getElementById("my_div");
div_container.title = data;
</script>
</body>
</html>
```

WinDbg then says:

```plain
0:024> s -a 0 L?80000000 aaaabaaacaaadaaa
0337a940  61 61 61 61 62 61 61 61-63 61 61 61 64 61 61 61  aaaabaaacaaadaaa
09edb960  61 61 61 61 62 61 61 61-63 61 61 61 64 61 61 61  aaaabaaacaaadaaa
09ee1840  61 61 61 61 62 61 61 61-63 61 61 61 64 61 61 61  aaaabaaacaaadaaa
0a24773c  61 61 61 61 62 61 61 61-63 61 61 61 64 61 61 61  aaaabaaacaaadaaa
```

2021-10-08 06:58 UTC, justinsteven commented
I've just realized this could also go in `util.fiddling`. Thoughts?

2021-10-25 22:36 UTC, justinsteven commented
Is there anything I can do to get this across the line? In the meantime can this please be given the label `hacktoberfest-accepted`

2021-10-31 23:38 UTC, Arusekk commented
Fiddling would be a better place I guess.

2022-01-24 11:07 UTC, Arusekk requested changes
I finally had time to review this thoroughly. I am now sure I understand (and agree with) everything I haven't mentioned.

2022-01-24 11:07 UTC, Arusekk commented on pwnlib/util/fiddling.py
> +        data = map(ord, data)
There is a universal cross-version way to handle this:
```suggestion
    data = bytearray(data)
```
not sure, but it is possible that we do it already in _need_bytes.

2022-01-24 11:07 UTC, Arusekk commented on pwnlib/util/fiddling.py
> +            res.append(packing._encode(s[p]))
Why packing._encode? Shouldn't we stick to UTF-16 for literal bytes, i.e. use `packing.p16(ord(s[p]))` too?

I guess from my basic tests that the non-unicode token is just a shorthand for a zero-upper unicode token, like `%E4 == %u00E4`, like python's infamous `'\xc0' == '\u00c0'` only creating confusion with `b'\xc0'`.
I also guess that new emoji and other high codepoints are always represented by strings of length 2 (`String.fromCodePoint(0x10ffff).length === 2`) so we could convert emoji stuff to surrogates in order to be strict (in Python `len("\U0010FFFF")==1`); not sure where it applies, but would be helpful if some CTF challenge needs emoji for some exotic reason.

I hate reading ECMAScript specs, so I only tested my Firefox, but if I were to write the standards, I would precisely define these cases for sure.

2022-01-24 11:07 UTC, Arusekk commented on pwnlib/util/packing.py
> +Module for packing and unpacking integers and data.
A revert for this file?

2022-01-24 11:07 UTC, Arusekk commented on pwnlib/util/fiddling.py
> +    padding = packing._need_bytes(padding)
Different ordering.

```suggestion
    padding = packing._need_bytes(padding)
    if len(padding) != 1:
        raise ValueError("Padding must be a single byte")
```

2022-04-20 14:39 UTC, Arusekk commented on pwnlib/util/packing.py
> +Module for packing and unpacking integers and data.
```suggestion
Module for packing and unpacking integers.
```

2022-04-20 14:39 UTC, Arusekk commented on pwnlib/util/packing.py
> +import string
```suggestion
```

2022-04-20 14:41 UTC, Arusekk commented on pwnlib/util/fiddling.py
> +            res.append(packing._encode(s[p]))
```suggestion
            res.append(packing.p16(ord(s[p])))
```

2022-04-20 14:43 UTC, Arusekk commented on pwnlib/util/fiddling.py
> +    s = packing._need_text(s)
```suggestion
    s = packing._decode(s)
```

2022-04-20 15:49 UTC, merged