Add libc to pwn template
Gallopsled/pwntools pull request #2082
Opened 2022-07-01 10:43 UTC by ghsi10

# Pwntools Pull Request

Thanks for contributing to Pwntools!  Take a moment to look at [`CONTRIBUTING.md`][contributing] to make sure you're familiar with Pwntools development.

Please provide a high-level explanation of what this pull request is for.

## Testing

Pull Requests that introduce new code should try to add doctests for that code.  See [`TESTING.md`][testing] for more information.

## Target Branch

Depending on what the PR is for, it needs to target a different branch.

You can always [change the branch][change] after you create the PR if it's against the wrong branch.

| Branch   | Type of PR                                                       |
| -------- | ---------------------------------------------------------------- |
| `dev`    | New features, and enhancements
| `dev`    | Documentation fixes and new tests
| `stable` | Bug fixes that affect the current `stable` branch
| `beta`   | Bug fixes that affect the current `beta` branch, but not `stable`
| `dev`    | Bug fixes for code that has never been released

[contributing]: https://github.com/Gallopsled/pwntools/blob/dev/CONTRIBUTING.md
[testing]: https://github.com/Gallopsled/pwntools/blob/dev/TESTING.md
[change]: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

## Changelog

After creating your Pull Request, please add and push a commit that updates the changelog for the appropriate branch.  
You can look at the existing changelog for examples of how to do this.

2022-08-15 10:42 UTC, Arusekk commented
What is the purpose of these changes?  When is it useful and how does it work?

2022-08-15 12:03 UTC, ghsi10 commented
It add a libc file argument to the pwn template.
pwn template --host HOST --port PORT **--libc=LIBC ./EXE**

2022-08-15 13:00 UTC, Arusekk commented
Thank you for replying, however I still do not know what the new argument does and why is it useful.  Could you provide an example exploit produced by such a modified template, and justify why it is done this way?

2022-08-15 21:52 UTC, ghsi10 commented
Of course, most CTFs provide the binary and libc.
As part of the exploit many times we have to take advantage of the fact that we have the appropriate libc.
For example if we want to do ret2libc we want to use libc.

Attached is an exploit example
[exp.zip](https://github.com/Gallopsled/pwntools/files/9340017/exp.zip)

2022-08-17 23:01 UTC, disconnect3d commented
I think adding libc argument makes sense, but the way it is proposed in this PR does not work. @ghsi10 have you tested your change at all?

With your change, we would just get `libc = os.path.basename(binary)` line printed out by the `pwn template` command. I think what you want is something like `libc = ELF({libc_repr})` if I understand the syntax correctly (I have not tested it of course, please do so!).

2022-08-19 11:17 UTC, ghsi10 commented
I updated the template to be correct.
I'm not sure how to compile and test it. I would appreciate an explanation :)

2022-08-19 13:54 UTC, Arusekk commented
The quick&dirty way: just find wherever your pwntools is located, replace the relevant file(s), and run `pwn template --whatever --args --you --added`.

The less messy way: `cd` into your cloned fork and run `python3 -m pwnlib.commandline.main template --whatever --args --and-so-on`.

2022-09-22 11:01 UTC, ghsi10 commented
Is there anything new with this?

2022-09-25 12:54 UTC, Arusekk commented
This clearly does not work. `libc_repr` is not defined, and therefore a NameError is raised every time `libc` is set.
I see that this could be a useful feature, but please please do test that your changes work before requesting a review.  It will save everyone's time, and reduce the feedback round-trips count.

2022-09-29 20:50 UTC, ghsi10 commented
@Arusekk it works for me locally now.
Thanks for the help :)

![image](https://user-images.githubusercontent.com/14124641/193139219-5a6a80ae-30d2-4775-bb7c-2b1af2677a4b.png)

2022-11-15 12:05 UTC, Arusekk commented
Great, now I can see that the template works in normal cases. However, imagine the libc is not called `libc.so.6` but instead `libc.'); evil_code() #.so.6` —what does the code do then? I see that this is unlikely etc, but we should do the same as we do for the EXE path, i.e. the `repr` thing. Please read the code carefully and copy relevant parts.

2022-12-28 22:42 UTC, Arusekk requested changes

2022-12-28 22:42 UTC, Arusekk commented on pwnlib/data/templates/pwnup.mako
> +libc = ELF('${libc}')
This must be done the same way binary_repr works now.

2023-07-24 17:29 UTC, Arusekk commented
Closing in favor of #2212.

2023-07-24 17:29 UTC, closed without merging