modified options in make_elf to disable newer GNU linker warnings
Gallopsled/pwntools pull request #2098
Opened 2022-08-19 20:49 UTC by tj-oconnor

# linker options

the stable/dev repositories of asm/make_elf throw when building ELFs due to an error with a newly implemented GNU linker warning that warns about LOAD segment with RWX permissions. Adding the ``--no-warn-rwx-segments`` and  ``--no-warn-execstack`` linker options remediates this issue 

See [kernel.org mailing list](https://lore.kernel.org/all/CACPK8Xe4hEB3wkRc4W2dNQ+ChonsKtWGCVPpoOFdjdfpbK88Mg@mail.gmail.com/T/) for explanation of these new gnu linker warnings

# error replication

>>> from pwn import *
>>> p = run_assembly('push 0xbad')
[ERROR] There was an error running ['/usr/bin/x86_64-linux-gnu-ld', '--oformat=elf32-i386', '-EL', '-m', 'elf_i386', '-z', 'execstack', '-o', '/tmp/pwn-asm-phbp53vv/step3', '/tmp/pwn-asm-phbp53vv/step2', '--section-start=.shellcode=0x10000000', '--entry=0x10000000', '-z', 'max-page-size=4096', '-z', 'common-page-size=4096']:
    It had this on stdout:
    /usr/bin/x86_64-linux-gnu-ld: warning: /tmp/pwn-asm-phbp53vv/step3 has a LOAD segment with RWX permissions
    
[ERROR] An error occurred while assembling:
       1: .section .shellcode,"awx"
       2: .global _start
       3: .global __start
       4: .p2align 2
       5: _start:
       6: __start:
       7: .intel_syntax noprefix
       8: push 0xbad
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/pwnlib/asm.py", line 710, in asm
        _run(linker + ldflags)
      File "/usr/local/lib/python3.10/dist-packages/pwnlib/asm.py", line 404, in _run
        log.error(msg, *args)
      File "/usr/local/lib/python3.10/dist-packages/pwnlib/log.py", line 424, in error
        raise PwnlibException(message % args)
    pwnlib.exception.PwnlibException: There was an error running ['/usr/bin/x86_64-linux-gnu-ld', '--oformat=elf32-i386', '-EL', '-m', 'elf_i386', '-z', 'execstack', '-o', '/tmp/pwn-asm-phbp53vv/step3', '/tmp/pwn-asm-phbp53vv/step2', '--section-start=.shellcode=0x10000000', '--entry=0x10000000', '-z', 'max-page-size=4096', '-z', 'common-page-size=4096']:
    It had this on stdout:
    /usr/bin/x86_64-linux-gnu-ld: warning: /tmp/pwn-asm-phbp53vv/step3 has a LOAD segment with RWX permissions
    
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/context/__init__.py", line 1577, in setter
    return function(*a, **kw)
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/runner.py", line 34, in run_assembly
    return ELF.from_assembly(assembly).process()
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/context/__init__.py", line 1577, in setter
    return function(*a, **kw)
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/elf/elf.py", line 402, in from_assembly
    return ELF(make_elf_from_assembly(assembly, *a, **kw))
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/context/__init__.py", line 1577, in setter
    return function(*a, **kw)
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/asm.py", line 524, in make_elf_from_assembly
    result = asm(assembly, vma = vma, shared = shared, extract = False, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/context/__init__.py", line 1577, in setter
    return function(*a, **kw)
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/asm.py", line 733, in asm
    log.exception("An error occurred while assembling:\n%s" % lines)
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/asm.py", line 710, in asm
    _run(linker + ldflags)
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/asm.py", line 404, in _run
    log.error(msg, *args)
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/log.py", line 424, in error
    raise PwnlibException(message % args)
pwnlib.exception.PwnlibException: There was an error running ['/usr/bin/x86_64-linux-gnu-ld', '--oformat=elf32-i386', '-EL', '-m', 'elf_i386', '-z', 'execstack', '-o', '/tmp/pwn-asm-phbp53vv/step3', '/tmp/pwn-asm-phbp53vv/step2', '--section-start=.shellcode=0x10000000', '--entry=0x10000000', '-z', 'max-page-size=4096', '-z', 'common-page-size=4096']:
It had this on stdout:
/usr/bin/x86_64-linux-gnu-ld: warning: /tmp/pwn-asm-phbp53vv/step3 has a LOAD segment with RWX permissions

2022-08-20 09:04 UTC, peace-maker commented
This needs some guard around the linker version, since unkown arguments don't appear to be ignored on older versions.

```
$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.34
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
$ ld --no-warn-rwx-segments
ld: unrecognized option '--no-warn-rwx-segments'
ld: use the --help option for usage information
$ ld --no-warn-execstack
ld: unrecognized option '--no-warn-execstack'
ld: use the --help option for usage information
```

2022-08-22 09:25 UTC, zachriggle approved these changes
LGTM

2022-08-26 21:09 UTC, tj-oconnor commented
Thank you. Updated to include a guard. Additionally, updated another location where it was necessary to add the new linker options.

2022-10-24 20:30 UTC, CmdP1rx commented
The regex does not pickup Kali Linux's and Garuda's versioning of **ld --version**:

Here is the example of such output

**GNU ld (GNU Binutils for Debian) 2.39
Copyright (C) 2022 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.**

2022-11-15 13:22 UTC, peace-maker commented
I'd suggest changing the regex to ` (\d+(?:\.\d+)+)`.

2022-11-15 14:13 UTC, Diff-fusion commented
Another option would be to execute `ld --no-warn-rwx-segments --help` and check the return status.

2022-12-04 14:30 UTC, heapcrash requested changes

2022-12-04 14:30 UTC, heapcrash commented on pwnlib/asm.py
> +def _linker_warns_rwx():
Please see the recommendation in #2140

2022-12-28 21:47 UTC, closed without merging