Add formats for hex
Gallopsled/pwntools pull request #2117
Opened 2022-10-17 20:18 UTC by marcan2020

# Add formats for hex
Add `-p` (`--prefix`) and `-s` (`--separator`) arguments for adding a prefix and/or a separator to the output of the hex command.

```bash
$ pwn hex ABCD
41424344
$ pwn hex ABCD --separator ' '
41 42 43 44
$ pwn hex ABCD --prefix '\x'
\x41\x42\x43\x44
$ pwn hex ABCD -p '0x' -s ' '
0x41 0x42 0x43 0x44
```

Relates to #2071.

2022-12-29 00:06 UTC, Arusekk requested changes
Please make sure that this code gets some coverage (no test required, but invoking it would look nice); it will be enough to add a command somewhere around here: https://github.com/marcan2020/pwntools/blob/dev/.github/workflows/ci.yml#L142

2022-12-29 00:06 UTC, Arusekk commented on pwnlib/commandline/hex.py
> +    parts = [s[i:i+n] for i in range(0, len(s), n)]
The same thing is done by [`util.iters.group`](https://docs.pwntools.com/en/latest/util/iters.html#pwnlib.util.iters.group) or [`util.lists.group`](https://docs.pwntools.com/en/latest/util/lists.html#pwnlib.util.lists.group) already.

2023-06-01 13:03 UTC, peace-maker approved these changes

2023-06-02 20:08 UTC, Arusekk commented on pwnlib/commandline/hex.py
> +    return separator.join(["%s%s" % (prefix, x) for x in group(2, hex_string)])
isn't it too complicated?
```suggestion
    return separator.join([prefix + x for x in group(2, hex_string)])
```

2023-06-04 20:23 UTC, merged