Fix `make_elf` on systems with GNU ld 2.39+
Gallopsled/pwntools pull request #2141
Opened 2022-11-28 00:14 UTC by clubby789

Fixes #2140

GNU ld 2.39 introduces a new warning which is always invoked by `ELF.from_bytes` and similar functions.

This PR detects affected versions of `ld` and adds an argument which ignores the warning.

2022-11-28 00:26 UTC, clubby789 commented
Pylint is failing because the existing error (`E:585,19: Unexpected keyword argument 'arch' in function call (unexpected-keyword-arg)`) has moved down by a few lines.

2022-11-28 01:11 UTC, clubby789 commented
Sorry for the commit/CI spam - I'm not able to reproduce the particular failiure locally

2022-11-28 12:05 UTC, peace-maker commented
This appears to be a duplicate of #2098

2022-11-28 13:56 UTC, clubby789 commented
Since the author of that PR hasnt responded, I've applied @Diff-fusion's suggestion of checking the return code of `ld --no-warn-rwx-segments --help` - it looks like many distros releases of `ld` have differently formatted version strings, and parsing them is probably going to be flaky.

2022-11-28 15:38 UTC, peace-maker commented
Nice, this looks more robust now. The same ld version introduced a warning about executable stacks too, so maybe adding `--no-warn-execstack` is in order like the other PR does?

2022-11-28 15:54 UTC, clubby789 commented
I didn't include that one here, as the release notes specify that the warning will not be issued if an executable stack is specifically requested (`-z execstack`), which is used here. Detecting it introduces another point of failure/delay while that argument is checked.

We could add it unconditionally, but it's _possible_ (while unlikely) some distros will compile with one flag but not the other.

2022-12-04 14:30 UTC, heapcrash requested changes

2022-12-04 14:30 UTC, heapcrash commented on pwnlib/asm.py
> +            arguments.append("--no-warn-rwx-segments")
Please see the recommendation in #2140

2022-12-28 21:47 UTC, closed without merging