Fix bug at ssh.py:process() - empty argv[0] Error (#2217)
Gallopsled/pwntools pull request #2234
Opened 2023-07-19 11:06 UTC by Youheng-Lue

Reopening #2225, since the Coverage tests didn't seem to handle changing the target branch correctly.

This addresses #2217 , a bug which disallowed us to use `ssh.py:process()` with an empty argv[0]

# Bug description
`ssh.py.process()` uses a python script to call `os.execve` to create a new process. `os.execve` disallows an empty argv.

# Fix
 This commit replaces `os.execve` with  `ctypes.CDLL(None).execve` to call the C-Library function directly which allows an empty argv.

2023-07-24 09:25 UTC, Youheng-Lue commented
Hi, just wanted to ask if there are any changes you require me to make to the pull request or is it ready to merge?

2023-07-24 17:09 UTC, Arusekk commented
For now I can only tell I am 90% sure that `environb` will break under py2.  I should find some time for a deeper review soon.

2023-07-24 17:40 UTC, goreil commented
> For now I can only tell I am 90% sure that `environb` will break under py2. I should find some time for a deeper review soon.

Wow, totally missed that. Thanks for the heads up! Fixed.

2023-07-27 07:40 UTC, peace-maker commented
https://github.com/Gallopsled/pwntools/pull/2225#issuecomment-1635984358

The code checks the environment variable name not the value.

2023-09-12 14:56 UTC, peace-maker requested changes

2023-09-12 14:56 UTC, peace-maker commented on pwnlib/tubes/ssh.py
> -os.execve(exe, argv, env)
Can we only use the ctypes workaround if `exe != argv[0]`?

2023-09-12 14:56 UTC, peace-maker commented on pwnlib/tubes/ssh.py
> +env_list = [key + b"=" + value for key, value in env.items()]
Please [add a check](https://github.com/python/cpython/blob/025995feadaeebeef5d808f2564f0fd65b704ea5/Modules/posixmodule.c#L6476) that `key` does not contain `=`.

2023-09-12 14:56 UTC, peace-maker commented on pwnlib/tubes/ssh.py
> +libc = ctypes.CDLL(None)
Do you have a reference of where `ctypes.CDLL` accepts `None` as `name` to get libc? Above we're using `ctypes.CDLL('libc.so.6')`.

2023-09-14 13:32 UTC, peace-maker approved these changes

2023-09-14 13:34 UTC, peace-maker requested changes

2023-09-14 13:34 UTC, peace-maker commented on pwnlib/tubes/ssh.py
> +        # Validate that all key of env do not contain '='
This comment seems like a left over.

2023-09-14 23:07 UTC, peace-maker approved these changes

2023-09-14 23:10 UTC, merged

2023-09-14 23:12 UTC, peace-maker commented
Thank you! This'll make e.g. overthewire solve scripts cleaner 🔥