Allow creating custom templates in user-config directory
Gallopsled/pwntools pull request #2257
Opened 2023-08-20 16:44 UTC by hweissi

This commit makes the `template` commandline tool try to get template files out of `~/.config/pwntools/templates` before using the ones shipped with the library.

This would people to fix issues like #2030 permanently on their machine, across updates.
Could also be used to import frequently used libraries automatically, or strip down the template to a more minimal one.

2023-08-20 20:24 UTC, peace-maker requested changes
This should be documented in the command help string as well.

2023-08-20 20:24 UTC, peace-maker commented on pwnlib/commandline/template.py
> +        directories      = [os.path.expanduser('.config/pwntools/templates/'), os.path.join(pwnlib.data.path, 'templates')],
The path should start with a `~` to expand to the home directory.

2023-08-20 20:44 UTC, peace-maker commented
Maybe adding a `--template` argument to override it per invocation is the nicest way to add this. Then we can mention the .config folder in the help string of that option.

2023-08-21 13:47 UTC, hweissi commented
I added a short help string, but it does not explain where to get the base template from. It isn't too hard to find, but still requires looking into the pwntools repo. I'm not sure where to document that though, seems a bit too much for an argument help string

2023-08-23 13:53 UTC, peace-maker commented
Cool, but I think it's weird to pass a directory where the template has to be named `pwnup.mako` as argument. I'd expect it to point to the template file itself. Can you change it to expect a path to a file and use basename to extract the template filename please?

For the .config folder we need to document the filename too.

2023-08-23 13:55 UTC, peace-maker commented
We could lookup the install location and add the full local path to the data/templates directory to the help? I'm not sure where else to document this either since it's very specific to the `pwn template` command.

2023-08-23 15:02 UTC, hweissi commented
I tried a version that falls back to the base template if the chosen template is invalid - it lead to pretty unclean code though. Letting it crash when the template path is invalid is probably cleaner, and also more clear to the user.

I also added code that displays the full path to the template in the argument description, but it's probably going to look weird in the documentation. Is there a way to see if the docs are being built in the code?

2023-09-11 15:32 UTC, hweissi commented
Bump

2023-09-12 12:11 UTC, peace-maker requested changes
Sorry for the delay! [Stack overflow](https://stackoverflow.com/questions/20843737/check-if-sphinx-doc-called-the-script) says you can check if you're building the docs using `if 'sphinx' in sys.modules:`. Maybe that works to say just `pwnlib/data/templates` when building docs?

2023-09-12 12:11 UTC, peace-maker commented on pwnlib/commandline/template.py
> +parser.add_argument('--base', help='Path to a custom base template. Defaults to \'~/.config/pwntools/templates/pwnup.mako\'. '
I think `--template` matches the matter better than `--base`. This isn't a base template, which is extended by other templates, but THE template used to generate the script. Yes `pwn template --template` looks weird, but I can't think of a better name.

The mention of the `.config` template folder should say something like "if it exists"? Right now it sounds like the default template is in the `~/.config` folder while saying the other default template is in yet another path :D

2023-09-13 13:26 UTC, hweissi commented
> Sorry for the delay! [Stack overflow](https://stackoverflow.com/questions/20843737/check-if-sphinx-doc-called-the-script) says you can check if you're building the docs using `if 'sphinx' in sys.modules:`. Maybe that works to say just `pwnlib/data/templates` when building docs?

That solution seems a bit hacky to me, but it works - I added it to the PR, as well as the other requested changes

2023-09-13 16:02 UTC, peace-maker approved these changes
Looks good, thank you!

2023-09-13 16:03 UTC, merged