Add a `flatten` argument to `ssh.libs`
Gallopsled/pwntools pull request #2268
Opened 2023-09-12 08:51 UTC by ValekoZ

This option makes us able to avoid getting the file tree of the remote server and just downloads the desired files in the output folder:

```python
>>> shell = ssh(host='example.org')
>>> shell.libs('/bin/sh', directory = 'libs', flatten = True)
{'/path/to/cwd/libs/libc.so.6': 22708292161536, '/path/to/cwd/libs/ld-linux-x86-64.so.2': 22708294139904, '/path/to/cwd/libs/dash': 0}
```

2023-09-12 12:43 UTC, peace-maker commented
We should emit a warning on duplicate files when the filename is equal but the remote path was different.

2023-09-12 13:37 UTC, ValekoZ commented
Do you think it should just emit a warning and skip the download ? Or should it renames the file to something like `{filename}_duplicate` and then `{filename}_duplicate2`, etc. ?

2023-09-12 14:39 UTC, peace-maker commented
I guess renaming them is better instead of discarding used libraries, but I'd switch to the unflattened structure anyways if this happens. We should log a warning in any case. I don't know how stable the order of the loaded libraries is in ldd and if you can be sure you always want the first matching library on every run.

2023-09-14 06:05 UTC, peace-maker commented
Can you document that fallback behaviour in the argument description please?

2023-09-14 06:18 UTC, ValekoZ commented
Yep, I just did it, sorry I forgot that

2023-09-14 06:19 UTC, peace-maker requested changes
Cool, it would be awesome if you could add tests for the function testing with`flatten` on and off and with and without duplicates.

We're using doctests, check out other examples in the function docs comments of other functions in the file!

2023-09-14 06:19 UTC, peace-maker commented on pwnlib/tubes/ssh.py
> +                if name in basenames:
This seems wrong, `in` checks if the value exists in the keys of the dictionary iirc.

2023-09-14 06:19 UTC, peace-maker commented on pwnlib/tubes/ssh.py
> +                    self.warning('Duplicate lib name, switching to unflattened file tree: %r' % name)
Can you output both conflicting remote paths here?

2023-09-14 07:04 UTC, ValekoZ commented on pwnlib/tubes/ssh.py
> +                if name in basenames:
Oh shit sorry, I was using a list at the beginning and then switched to dict in order to avoid to recompute the basename :(
I will fix that

2023-10-11 19:57 UTC, ValekoZ commented
I just tried to create unit tests for this functionnality, but I was wondering what design did you like better ?
I have the choice between creating minimal ELF files dynamically using lief for creating a binary with 2 libs with the same filename, or just dropping the binaries I created in the repo so that I don't have to add a dependency for the tests

2023-10-17 18:54 UTC, peace-maker commented
I think adding another small binary to the `pwnlib/data/elf` folder seems fair. It doesn't have to be runnable I guess, so referencing duplicate not-existing libraries might be fine.

2023-10-23 14:16 UTC, ValekoZ commented
Can you check that I added the tests correctly ? It says all tests passed but I'm not even sure the tests were run .. 😅

2023-11-11 22:36 UTC, peace-maker commented
I think it's saner to abort on duplicate libraries instead of silently falling back to unflattened output. The locations would be different than what the script expects and it would break anyways.
> but I'd switch to the unflattened structure anyways if this happens

I was talking about me using this feature, not how I'd imagine it to behave automatically. Sorry for the confusion.

You can test if the tests are run by adding something obviously broken and see if it breaks.

2023-12-04 21:03 UTC, peace-maker requested changes
Nice, the CI ran now and revealed some problems with your tests. Can you `strip` the binaries to reduce size please?

2023-12-04 21:03 UTC, peace-maker commented on pwnlib/tubes/ssh.py
> +            >>> s.cwd = f'{pwnlib.data.elf.path}/ssh_libs'
Please create an `__init__.py` file and use `pwnlib.data.elf.ssh_libs.get("duplicate")` etc. below. Check the the `__init__.py` in one of the other sub folders. The cwd has to be writeable and it apparently isn't in CI, when you change to the pwnlib data directory.

2023-12-06 12:41 UTC, ValekoZ commented
Apparently, the elf I pushed are corrupted (I can't run `ldd` on them), I'll try to fix that ^^

2023-12-06 15:38 UTC, ValekoZ commented
Sorry for all the commits, I can't run the tests on my computer (it doesn't work, I don't know why)
I still have an issue and I don't understand why, I stop for today I'll check that later ^^

2024-01-02 09:58 UTC, peace-maker commented
@Arusekk can you have a look please?

2024-02-09 15:05 UTC, peace-maker commented
Bleh, I've tried to get the tests to work nicely but don't want to wrestle with -rpath $ORIGIN and friends anymore. I'll add this now and deal with the test again later.

2024-02-09 15:06 UTC, merged