Make pwn template always set context.binary
Gallopsled/pwntools pull request #2279
Opened 2023-09-26 11:34 UTC by FlorianKothmeier

```

# Pwntools Pull Request

Thanks for contributing to Pwntools!  Take a moment to look at [`CONTRIBUTING.md`][contributing] to make sure you're familiar with Pwntools development.

Please provide a high-level explanation of what this pull request is for.

## Testing

Pull Requests that introduce new code should try to add doctests for that code.  See [`TESTING.md`][testing] for more information.

## Target Branch

Depending on what the PR is for, it needs to target a different branch.

You can always [change the branch][change] after you create the PR if it's against the wrong branch.

| Branch   | Type of PR                                                       |
| -------- | ---------------------------------------------------------------- |
| `dev`    | New features, and enhancements
| `dev`    | Documentation fixes and new tests
| `stable` | Bug fixes that affect the current `stable` branch
| `beta`   | Bug fixes that affect the current `beta` branch, but not `stable`
| `dev`    | Bug fixes for code that has never been released

[contributing]: https://github.com/Gallopsled/pwntools/blob/dev/CONTRIBUTING.md
[testing]: https://github.com/Gallopsled/pwntools/blob/dev/TESTING.md
[change]: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

## Changelog

After creating your Pull Request, please add and push a commit that updates the changelog for the appropriate branch.  
You can look at the existing changelog for examples of how to do this.

2023-09-26 17:06 UTC, peace-maker requested changes
Thank you! This might help simple usecases of just invoking `pwn template`.

This feels like we need to improve the documentation around how to use the template generator tool. When using the plain invocation instead of providing the target binary during `pwn template ./challenge` invocation, the path has to be edited into the generated script manually, which seems redundant and like a misuse of the template generator :(

This also shifts the requirement to change the generated script right away to remote-only exploit templates generated using `pwn template --host abc.com --port 1234` since it'd try to access the `./path/to/binary` dummy file now, so you'd have to comment out that line and remember to add the `context.update(arch='XXX')` back manually.

Maybe the best compromise would be to keep the current output of not using `context.binary` if there is no binary given and `host` is set.

2023-09-26 17:06 UTC, peace-maker commented on pwnlib/data/templates/pwnup.mako
> +exe = context.binary = ELF(${binary_repr})
This should keep the `args.EXE` override possibility. So it can be simplified even more by just always using the same line.

2023-09-27 12:16 UTC, FlorianKothmeier commented
Thanks for the feedback!

What's the preferred development approach here? Should changes from the review stay as a separate commit or be squashed into the first one?

2023-09-27 12:55 UTC, peace-maker commented
Separate commits are fine for such small changes like this. We squash the whole PR branch before merging.

2023-11-29 21:31 UTC, peace-maker commented
Is #2309 an acceptable solution to this problem too?

2023-11-30 16:54 UTC, FlorianKothmeier commented
@peace-maker Yes, that patch sounds good. However, this still leaves he old behavior when the challenge files could not be determined automatically. But this is probably good enough

2023-11-30 17:20 UTC, peace-maker commented
We can still add the change to include `context.binary` when no exe was set nor found. I'd still like to avoid crashing when trying to open the `'./path/to/binary'` file if you only specify a remote host and port. There often are remote-only challenges without a handout.

2023-12-30 17:41 UTC, FlorianKothmeier commented
@peace-maker I just added a commit that implements the fallback you suggested for remote-only challenges. Sorry that it took me this long

2023-12-30 18:31 UTC, peace-maker approved these changes
Thank you, I like it!

2023-12-30 18:35 UTC, merged