Make sure winexec is 16 byte aligned and add nCmdShow option
Gallopsled/pwntools pull request #2308
Opened 2023-11-26 09:00 UTC by kizzx2

# Pwntools Pull Request

Thanks for contributing to Pwntools!  Take a moment to look at [`CONTRIBUTING.md`][contributing] to make sure you're familiar with Pwntools development.

WinExec currently errors out when tested on Windows 11 x64. After some diagnosis it appears that `pushstr` aligns to 8 bytes but Windows calling convention [requires 16 byte](https://learn.microsoft.com/en-us/cpp/build/stack-usage?view=msvc-170). Perhaps this was not enforced in previous versions of Windows but apparently that is the standard requirement.

Example programs to reproduce the issue:

```python
import pwn

pwn.context.arch = "amd64"
sc = pwn.asm(pwn.shellcraft.amd64.windows.winexec("calc.exe"))
print("""unsigned char buf[] = {""" + ", ".join(map(hex, sc)) + """};""")
```

```c
#include <Windows.h>
#include <stdio.h>

unsigned char buf[] = {}; // ... paste the shell code here

int main() {
    void *exec = VirtualAlloc(0, sizeof(buf), MEM_COMMIT, PAGE_EXECUTE_READWRITE);
    memcpy(exec, buf, sizeof(buf));
    ((void(*)())exec)();
    printf("Done!\n");
    return 0;
}
```

Screenshot:

![image](https://github.com/Gallopsled/pwntools/assets/92614/3447f69f-dbdf-4411-872f-c46cb7c7e417)

As seen above, `rsp` is not 16 byte aligned causes `movaps` to error out

## Testing

Pull Requests that introduce new code should try to add doctests for that code.  See [`TESTING.md`][testing] for more information.

## Target Branch

Depending on what the PR is for, it needs to target a different branch.

You can always [change the branch][change] after you create the PR if it's against the wrong branch.

| Branch   | Type of PR                                                       |
| -------- | ---------------------------------------------------------------- |
| `dev`    | New features, and enhancements
| `dev`    | Documentation fixes and new tests
| `stable` | Bug fixes that affect the current `stable` branch
| `beta`   | Bug fixes that affect the current `beta` branch, but not `stable`
| `dev`    | Bug fixes for code that has never been released

[contributing]: https://github.com/Gallopsled/pwntools/blob/dev/CONTRIBUTING.md
[testing]: https://github.com/Gallopsled/pwntools/blob/dev/TESTING.md
[change]: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

## Changelog

After creating your Pull Request, please add and push a commit that updates the changelog for the appropriate branch.  
You can look at the existing changelog for examples of how to do this.

2023-11-26 10:50 UTC, Arusekk commented
Email z niedzieli 26 listopada 2023 od Chrisa Yuena:
> WinExec currently errors out when tested on Windows 11 x64. After some diagnosis it appears that `pushstr` aligns to 8 bytes but Windows calling convention [requires 16 byte](https://learn.microsoft.com/en-us/cpp/build/stack-usage?view=msvc-170). Perhaps this was not enforced in previous versions of Windows but apparently that is the standard requirement.

Not sure this is correct. I would prefer the stack move to be in a separate variable, and then the extra alignment to be just `stack_move & 8`, because the tons of math involved seem too convoluted to read.

I also intend to stress that Windows is not a primary exploitation target for pwntools, as there are better tools for that (metasploit for instance), and there is no easy way to test the shellcraft payloads on the CI. I see that the payloads are used, which is great, because I did not even expect that. Thanks for taking your time to fix it.

-- 
Wysłane z mojego urządzenia Sailfish

2023-11-26 15:39 UTC, kizzx2 commented
Thanks for the reply!

> as there are better tools for that (metasploit for instance)

My experience suggests otherwise. It is extremely convoluted, if not impossible (I never managed to get it work after some trials and errors) to get any Metaploit shellcode to work on modern Windows without Defender flagging it, due to its popularity. (That's how I landed here ;)

Metasploit's address loader with its customized "hashing algorithm" is probably too popular. Even something like `msfvenom -p windows/x64/exec CMD=calc.exe` just wouldn't work even with layers of encoding / encryptions that bloat a 900 byte shellcode into 5000 (Happy to learn if there's something I missed. I guess it might work if the msf payload is broken into parts with some tricky jmps in between -- but then might as well handcode the whole thing)

> I would prefer the stack move to be in a separate variable, and then the extra alignment to be just `stack_move & 8`, because the tons of math involved seem too convoluted to read.

Anyway, regarding this PR -- happy to change it in a way that's more obvious but not sure what you meant by a "separate variable"? This is what the math is basically trying to do:

1. `align(8, len(cmd) + 1)` This how much `amd64.pushstr` would have advanced the stack. I believe the original code was also bugged that the null byte was not accounted for. `pushstr` in the default param would have added a null byte so we need to account for it here as well, that's why `+1`.
2. `align(8, len(cmd) + 1) // 8 % 2`

| `align(8, len(cmd)+1)` | Output |
|-|-|
| 8 | 1 |
| 16 | 0 |
| 24 | 1 |
| 32 | 0 |

3. Basically, if `pushstr` moved us forward an 8-byte aligned value on the stack (instead of 16), then the above would evaluate to `1`

4. Before `pushstr`, the stack is *already 8-byte aligned*([https://learn.microsoft.com/en-us/cpp/build/stack-usage?view=msvc-170])(ref)) due to the shellcraft not doing the `push rbp` "function prolog".

5. Thus the logic is

    - If `pushstr` pushed us through a 8-byte multiple, then we'll be 16-byte aligned
    - If `pushstr` pushed us through an 16-byte multiple, then we need to push another 8 byte

6. From `5`, we will basically invert the result of step `3` by doing `^ 1`. So the final expression is

```python
align(8, len(cmd) + 1) // 8 % 2 ^ 1 * 8 # * 8 because we do 8 bytes multiple
```

> and there is no easy way to test the shellcraft payloads on the CI

Yes, thus tried to add screenshots and sufficient test codes so this can be hopefully easier to verify.

2023-11-30 17:38 UTC, peace-maker requested changes
Good catch, thank you!
The shellcode should be null and newline free and so those dynamic stack shifts feel bad. Could we get away with some `and rsp, -32` to align it down? 
https://github.com/masthoon/pwintools/blob/master/pwintools.py#L951

2023-11-30 17:38 UTC, peace-maker commented on pwnlib/shellcraft/templates/amd64/windows/winexec.asm
> +    mov rdx, ${cmd_show}
```suggestion
    ${amd64.mov('rdx', cmd_show)}
```

2023-12-08 11:47 UTC, kizzx2 commented
Sure, just pushed that please take a look

2023-12-11 14:34 UTC, peace-maker requested changes

2023-12-11 14:34 UTC, peace-maker commented on pwnlib/shellcraft/templates/amd64/windows/winexec.asm
> +    or rsp, 8
This seems inverted now and `rsp` doesn't land on the old value before the `pushstr` neither on `cmd.exe` nor `calc.exe`.

I'm testing this under linux by commenting out the `getprocaddress` and `call rsi` instructions and running `shellcraft -d amd64.windows.winexec calc.exe` in a shell if that makes a difference.

2023-12-12 15:31 UTC, peace-maker commented
Thanks, this looks good now. The only problem I still see with this shellcode (while we're at it) is the `add` instruction inserting null bytes for longer commands. How is this solved in similar places in shellcraft? The easiest solution would be to do
```
${amd64.mov('rcx', stack_frame + stack_frame_align)}
add rsp, rcx
```
to let `mov` handle the value.

2023-12-12 17:53 UTC, peace-maker approved these changes

2023-12-14 15:39 UTC, merged