add native websocket support
Gallopsled/pwntools pull request #2350
Opened 2024-02-18 06:38 UTC by ksshen0000

Add native support for websocket.

this file are derived from pwntools-tube-websocket by frankli0324 under the MIT License. 
https://gist.github.com/frankli0324/795162a14be988a01e0efa0531f7ac5a

I haven't figure out how to use sphinx and doctest, so my test cannot be run correctly at this time.
I need some help on configuring the test.

2024-02-20 20:10 UTC, peace-maker requested changes
Thank you for bringing this in! There are several things we need to consider before merging which I've mentioned inline.

Hi @frankli0324

2024-02-20 20:10 UTC, peace-maker commented on pwnlib/tubes/wstube.py
> +        >>> ws = wstube('wss://echo.websocket.events')
Can we host a basic echo server ourselves in ci instead of relying on an external service? Those tend to be flakey and disturb the testing flow from time to time.

2024-02-20 20:10 UTC, peace-maker commented on CHANGELOG.md
> +- [#2350][2350] add native websocket support
Please add new entries to the bottom of the list

2024-02-20 20:10 UTC, peace-maker commented on docs/source/tubes/wstube.rst
> +   from websocket import WebSocket, ABNF, WebSocketException, WebSocketTimeoutException
This isn't necessary since it's not used in the doc tests themselves

2024-02-20 20:10 UTC, peace-maker commented on pwnlib/tubes/wstube.py
> +        headers (dict): The same headers as the websocket protocol.
Aren't those additional headers to pass around?
How could we test this?

2024-02-20 20:10 UTC, peace-maker commented on pwnlib/tubes/wstube.py
> +        self.sock.connect(url, header=headers)
I think it is worth it to forward other [useful arguments](https://websocket-client.readthedocs.io/en/latest/examples.html#setting-common-header-values) to the constructor like `host`, `origin`, `cookie`, and `subprotocols`. As well as the other ones.

2024-02-20 20:10 UTC, peace-maker commented on pwnlib/tubes/wstube.py
> +
Maybe add a magic `__call__` handler to forward calls to the underlying web socket instance like `ping()`

Some `__getattr__` forward to e.g. get the optional close reason of the remote after the server closed the connection would be cool too.

2024-02-20 20:10 UTC, peace-maker commented on pwnlib/tubes/wstube.py
> +    def close(self):
It should be possible to specify the web socket close reason

2024-02-20 20:10 UTC, peace-maker commented on pwnlib/tubes/wstube.py
> +        self.sock.connect(url, header=headers)
Handling the proxy configured in `context.proxy` would be great too!

2024-02-20 20:10 UTC, peace-maker commented on pwnlib/tubes/wstube.py
> +    def recv_raw(self, numb):
`can_recv_raw` needs to be implemented too to handle timeouts in the tube model.

2024-03-28 01:53 UTC, minpeter commented
Is anyone working on this? I hope it will be merged by the third 2024 Q3 at the latest.

If there are no contributors working on it, I will try it.

2025-08-28 12:33 UTC, peace-maker commented
@minpeter Please open a new pull request if you start working on this. Closing for now since this has gone stale, feel free to reopen if you continue yourself @ksshen0000!

2025-08-28 12:33 UTC, closed without merging