Add functions for retrieving process mappings
Gallopsled/pwntools pull request #2371
Opened 2024-03-21 06:57 UTC by k4lizen

For: #2369 
+ implement `process.maps` which is a wrapper around `util.proc.memory_maps`
    + calls on self.pid, parses string address field and permissions field 
+ `get_mapping` function which finds mappings given a "path" to look
+ make `stack_mapping`, `heap_mapping`, `vdso_mapping`, `vvar_mapping`, `elf_mapping` which hook into `get_mapping`, and `libc_mapping`, `musl_mapping`
    + they return all the data that `util.proc.memory_maps` returns (so lots!)
+ `_location_from_mappings` combines consecutive mappings into an offest and address field
    + since e.g. elf and libc constitute multiple mappings, but this extra information is often not needed 
+ `get_mapping_location` which calls `_location_from_mappings`
+ `stack_location`, `heap_location`, `vdso_location`, `vvar_location`, `elf_location` and `libc_location`, `musl_location`
    + `libc_location()` essentially does the same thing as `libc` but gives the size as well
+ a `mapping_location` class for returns (and dot access)

Also Closes #2370

2024-03-21 07:07 UTC, k4lizen commented
Oh didn't know it had to support python2.7

2024-03-21 07:45 UTC, k4lizen commented
@peace-maker 
> Next to the hardcoded properties, having a shortcut to receive the base address of any mapping without having to filter the .libs() result manually would be great too.

Not sure what exactly you meant by this. `get_mapping_location` probably does that? Though the `path_value` does need to be an exact match.

2024-03-21 17:43 UTC, peace-maker commented
Yes, I was imagining a parameter to .libs() to get the base address of the passed lib instead of a dict.

2024-03-21 18:49 UTC, k4lizen commented
Sorry for late push, `address_mapping` is a good function for this PR.
> Yes, I was imagining a parameter to .libs() to get the base address of the passed lib instead of a dict.

So do I leave it as is, change the functions I added, or add an overload to `.libs()` which takes in an additional argument and returns only the base address?
It is non-trivial for the user to e.g. find the size/end location of libc if we just return the base address, so that is something that would be nice to have in some form somewhere.

2024-04-01 17:20 UTC, peace-maker requested changes
Thank you! I've only some suggestions around the docs.

2024-04-01 17:20 UTC, peace-maker commented on pwnlib/tubes/process.py
> +        """stack_mapping(path_value, single=True) -> mapping
function name typo in comment

2024-04-01 17:20 UTC, peace-maker commented on pwnlib/tubes/process.py
> +        Runs get_mapping_location('[stack]').
Can you add references to the function they're wrapping to all of these please?
:meth:`.process.get_mapping_location`

2024-04-01 17:20 UTC, peace-maker commented on pwnlib/tubes/process.py
> +            path_value(str): The path used to find the mapping,
maybe mention it is an exact match?

2024-04-02 01:49 UTC, k4lizen commented
Done

2024-04-21 21:00 UTC, peace-maker commented
I just noticed this doesn't have any tests. Can you add doctest examples to all functions you added please? I'll try to add them eventually if you don't have the time :)

2024-04-22 14:34 UTC, k4lizen commented
I can add them. 
Though I'm not sure exactly how I would test for musl. Any recommendations on that front? 
The best way to do the doctest is probably by inspecting /proc/<pid>/maps and comparing it with pwntools output (though I'm pretty sure the dependancy we pull in for the mappings is inspecting /maps itself xd). I'll do an IO operation before the check so the process has time to load libc, heap etc.

By the way I forgot to add the `private` and `shared` fields to the `permissions` struct so I'll do that as well.

2024-04-22 15:19 UTC, peace-maker commented
Maybe we can get away with stubbing out the expected output using `...` and ELLIPSIS instead of checking for the exact values. psutil parses /proc too indeed.
For musl we could install `musl-tools` and build a simple test application in CI? We already have testing binaries in the `pwnlib/data/elf` folder. Those should probably be rebuilt dynamically instead of having binaries in git but that's another problem.

2024-04-22 15:54 UTC, k4lizen commented
> Maybe we can get away with stubbing out the expected output using ... and ELLIPSIS instead of checking for the exact values.

I don't see how that would help with musl, like if I call `p.musl_mapping()` it will just return None. I mean I can ... the whole output but that would IMO be worse then not having any tests for that.

> For musl we could install musl-tools and build a simple test application in CI? We already have testing binaries in the pwnlib/data/elf folder.

Sounds good, though I don't really know CI so I can't help you there.

2024-04-22 18:36 UTC, k4lizen commented
A doctest failed but it isnt mine?

2024-04-23 00:31 UTC, k4lizen commented
^ Other than that, I think thats it. (you can add the musl doctests after you do the musl-tools stuff I guess).

Btw, after thinking about it a bit (and while making the tests), I feel like the various something_location() functions are redundant and should probably be removed. That use-case was something I needed in my project but `address_mapping` now does what I need and the niche of "has multiple mappings in memory that are continous and cares about what their total size is" is too narrow, especially since just doing something like
```python
libc_mappings = p.libc_mapping(single=False)
size = libc_mappings[-1].end - libc_mappings[0].start
```
is easy enough. Also calling `vdso_location()` instead of `vdso_mapping()` is simply slower and returns less information, since vdso will only ever by one mapping, so it might actually be harmful to leave it in.

2024-04-30 11:06 UTC, peace-maker commented
Yes, please remove redundant API. Maybe returning some class instead of a simple mapping list which has a function to give you the total mapping size? Don't know how usable that is

2024-04-30 17:34 UTC, k4lizen commented
Okay so since vvar and vdso are only one mapping and stack and heap don't have contiguity guarantees it only makes sense from a user perspective to ask for the size of shared libraries (and the elf), so I replaced all the `location` stuff with `lib_size()` which does what it says (seemed simpler than a class approach).

2024-04-30 17:40 UTC, k4lizen commented
If you agree with the changes, the PR is done / ready for (re)review.

2024-04-30 20:27 UTC, k4lizen commented
Oh and as I said, it might be good to look into why https://github.com/Gallopsled/pwntools/actions/runs/8789031621/job/24117819520 failed.

2024-08-06 09:10 UTC, peace-maker approved these changes
Cool! Thank you for pushing through with this 😅

2024-08-06 09:10 UTC, merged