libcdb: add `offline_only` to `search_by_symbol_offsets`
Gallopsled/pwntools pull request #2388
Opened 2024-04-14 10:24 UTC by the-soloist

# Pwntools Pull Request

Thanks for contributing to Pwntools!  Take a moment to look at [`CONTRIBUTING.md`][contributing] to make sure you're familiar with Pwntools development.

Please provide a high-level explanation of what this pull request is for.

## Testing

Pull Requests that introduce new code should try to add doctests for that code.  See [`TESTING.md`][testing] for more information.

## Target Branch

Depending on what the PR is for, it needs to target a different branch.

You can always [change the branch][change] after you create the PR if it's against the wrong branch.

| Branch   | Type of PR                                                       |
| -------- | ---------------------------------------------------------------- |
| `dev`    | New features, and enhancements
| `dev`    | Documentation fixes and new tests
| `stable` | Bug fixes that affect the current `stable` branch
| `beta`   | Bug fixes that affect the current `beta` branch, but not `stable`
| `dev`    | Bug fixes for code that has never been released

[contributing]: https://github.com/Gallopsled/pwntools/blob/dev/CONTRIBUTING.md
[testing]: https://github.com/Gallopsled/pwntools/blob/dev/TESTING.md
[change]: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

## Changelog

After creating your Pull Request, please add and push a commit that updates the changelog for the appropriate branch.  
You can look at the existing changelog for examples of how to do this.

2024-05-12 12:32 UTC, peace-maker requested changes
Cool, thank you for working on this!

2024-05-12 12:32 UTC, peace-maker commented on pwnlib/libcdb.py
> +                matched += 1
We can speed this up by aborting this loop once there was a mismatch.

2024-05-12 12:32 UTC, peace-maker commented on pwnlib/libcdb.py
> +        return search_by_build_id(matching_list[0]['buildid'], unstrip=unstrip)
Maybe make sure to pass the `offline_only` argument through here and the other `search_by_build_id` calls in this function. I think it aborts when finding it offline before trying online, but just to be sure for the future.

2024-05-12 12:32 UTC, peace-maker commented on pwnlib/libcdb.py
> +        if select_index > 0 and select_index <= len(matching_list):
Is the `Path.rglob` order stable? Otherwise selecting the result by index might not work consistently here.

2024-05-14 02:40 UTC, the-soloist commented
Thank you for pointing out problems. I have completed the modifications.

2024-05-23 14:07 UTC, peace-maker approved these changes

2024-05-23 14:57 UTC, merged